Attempt fixing build after switching to crazy-max/ghaction-import-gp
We currently get the below error:

```
anaml_0.0.47_SHA256SUMS.sig
  ⨯ release failed after 6m20s               error=sign: gpg failed: exit status 2: gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device

Error: The process '/opt/hostedtoolcache/goreleaser-action/1.10.2/x64/goreleaser' failed with exit code 1
```

Some cryptic github issues look like downgrading to
crazy-max/ghaction-import-gp@v4 may work